name: CI - Main

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Restore
        run: dotnet restore Maliev.CommerceService.slnx
      - name: Build
        run: dotnet build Maliev.CommerceService.slnx --configuration Release --no-restore
      - name: Test
        run: dotnet test Maliev.CommerceService.slnx --configuration Release --no-build --verbosity normal
